apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: letsgo
  name: letsgo
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 7
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: letsgo
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: letsgo
        env: prod
    spec:
      containers:
      - image: docker.io/vishnu930417/minikube:latest
        imagePullPolicy: Always
        name: letsgo
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        livenessProbe:
          httpGet:
            path: /liveness
            port: 8080
          failureThreshold: 1
          periodSeconds: 60
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8080
          failureThreshold: 1
          periodSeconds: 60
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30