apiVersion: v1
kind: Service
metadata:
  labels:
    app: letsgo
  name: letsgo
  namespace: default
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: letsgo
  type: ClusterIP